config/routes.rb
Rails.application.routes.draw do
	root 'pedidos#index'
	get 'pedidos/reporte'
	
  resources :pedidos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: [:show, :edit, :update, :destroy]

  # GET /pedidos
  # GET /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1
  # GET /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos
  # POST /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Pedido was successfully created.' }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1
  # PATCH/PUT /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: 'Pedido was successfully updated.' }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1
  # DELETE /pedidos/1.json
  def destroy
    @pedido.destroy
    respond_to do |format|
      format.html { redirect_to pedidos_url, notice: 'Pedido was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def reporte 
  @pedido = Pedido.all
  @pedidoporcantidad = @pedido.sort_by(&:cantidad)
  @pedidoporprecio = @pedido.sort_by(&:precio)
  @pedidoportalla = @pedido.sort_by(&:talla)
end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pedido_params
      params.require(:pedido).permit(:color, :talla, :modelo, :cantidad, :precio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/layouts/application.html.erb
</html>
<!DOCTYPE html>
<html lang="en">

<body>
<ul>
<li><a href="/pedidos">Home</a></li>
<li><a href="/pedidos/new">New Pedido</a></li>
<li><a href="/pedidos/reporte">Reporte</a></li>

<li style="float: right;><a class="active" href="#about"></a></li>
</ul>
</body>
<head>

  <title>CATALOGO </title>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <head>
    
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
</head>
<body>
<ima><img src=https://st2.depositphotos.com/3849181/6036/v/450/depositphotos_60362677-stock-illustration-logo-shoes.jpg width="120" height="110"></ima>
<div class="container" style="text-align: center;">
 <h1>CATALOGO </h1>
  <h2> venta de zapatos</h2>
<br>
<div class="jumbotron text-center">
  
    <%= yield %>
</div>
</div>
   
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <h3>zapatillas</h3>
     <img src=http://ferraro.com.ar/Image/0/450_450-2714791%20(dd).jpg width="200" height="150" >

    </div>
    <div class="col-sm-4">
      <h3>Tennis</h3>
   <img src=https://assets.liverpool.com.mx/assets/images/categorias/zapatos/el-zapatos.jpg width="200" height="150">

    </div>
    <div class="col-sm-4">
      <h3>zapatos de niño</h3>        
    <img src=http://cdn01.pisamonas.es/media/catalog/product/cache/3/image/9df78eab33525d08d6e5fb8d27136e95/0/0/0021_zapatillas_ninos_de_cordones.jpg width="200" height="160">
    </div>
  </div>
</div>

</body>
</html>

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido, local: true) do |form| %>
  <% if pedido.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
      <% pedido.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :pedido_color %>
  </div>

  <div class="field">
    <%= form.label :talla %>
    <%= form.number_field :talla, id: :pedido_talla %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo, id: :pedido_modelo %>
  </div>

  <div class="field">
    <%= form.label :cantidad %>
    <%= form.number_field :cantidad, id: :pedido_cantidad %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio, id: :pedido_precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/edit.html.erb
<h1>Editing Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Show', @pedido %> |
<%= link_to 'Back', pedidos_path %>

app/views/pedidos/index.html.erb
<p id="notice"><%= notice %></p>



<table class="table">
  <thead class="thead-inverse">
  
    <tr>
      <th>Color</th>
      <th>Talla</th>
      <th>Modelo</th>
      <th>Cantidad</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pedidos.each do |pedido| %>
      <tr>
        <td><%= pedido.color %></td>
        <td><%= pedido.talla %></td>
        <td><%= pedido.modelo %></td>
        <td><%= pedido.cantidad %></td>
        <td><%= pedido.precio %></td>
        <td><%= link_to 'Show', pedido %></td>
        <td><%= link_to 'Edit', edit_pedido_path(pedido) %></td>
        <td><%= link_to 'Destroy', pedido, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pedido', new_pedido_path %>
<%= link_to 'New reporte', pedidos_reporte_path %>

app/views/pedidos/new.html.erb
<h1>New Pedido</h1>

<%= render 'form', pedido: @pedido %>

<%= link_to 'Back', pedidos_path %>

app/views/pedidos/reporte.html.erb
<table class="table">
  <thead class="thead-inverse">
    <hr>
    <tr>
      <th>Color</th>
      <th>Talla</th>
      <th>Modelo</th>
      <th>Cantidad</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <% @pedidoporcantidad.each do |pedido| %>
      <tr>
      
        <td><%= pedido.color %></td>
        <td><%= pedido.talla %></td>
        <td><%= pedido.modelo %></td>
        <td><%= pedido.cantidad %></td>
        <td><%= pedido.precio %></td>
    
      </tr>
    <% end %>
  </tbody>
</table>
  <% pedidocantidad = @pedidoporcantidad.first %>
  <% pedidocantidad1 = @pedidoporcantidad.last %>
<h3> la cantidad mas baja es:</h3> <h4><%= pedidocantidad.cantidad %> </h4>
<h3> la cantidad mas alta  es:</h3> <h4><%= pedidocantidad1.cantidad%> </h4>
<hr>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Color</th>
      <th>Talla</th>
      <th>Modelo</th>
      <th>Cantidad</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <% @pedidoporcantidad.each do |pedido| %>
      <tr>
      
        <td><%= pedido.color %></td>
        <td><%= pedido.talla %></td>
        <td><%= pedido.modelo %></td>
        <td><%= pedido.cantidad %></td>
        <td><%= pedido.precio %></td>
    
      </tr>
    <% end %>
  </tbody>  
</table>
 <% pedidoprecio = @pedidoporprecio.first %>
<% pedidoprecio1 = @pedidoporprecio.last %>
<h3> El precio más barato es:</h3> <h4><%= pedidoprecio.precio %> </h4>
<h3> El precio más caro es:</h3> <h4><%= pedidoprecio1.precio %> </h4>
<hr>
<table class="table">
  <thead class="thead-inverse">
    <tr>
      <th>Color</th>
      <th>Talla</th>
      <th>Modelo</th>
      <th>Cantidad</th>
      <th>Precio</th>
    </tr>
  </thead>
  <tbody>
    <% @pedidoporcantidad.each do |pedido| %>
      <tr>
      
        <td><%= pedido.color %></td>
        <td><%= pedido.talla %></td>
        <td><%= pedido.modelo %></td>
        <td><%= pedido.cantidad %></td>
        <td><%= pedido.precio %></td>
    
      </tr>
    <% end %>
  </tbody>  
</table>

 <% pedidotalla = @pedidoportalla.first %>
<% pedidotalla1 = @pedidoportalla.last %>
<h3> la talla  más chica es:</h3> <h4><%= pedidotalla.talla %> </h4>
<h3> El talla mas grande es:</h3> <h4><%= pedidotalla1.talla %> </h4>

<%= link_to 'New Pedido', new_pedido_path %>

app/views/pedidos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Color:</strong>
  <%= @pedido.color %>
</p>

<p>
  <strong>Talla:</strong>
  <%= @pedido.talla %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @pedido.modelo %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @pedido.cantidad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @pedido.precio %>
</p>

<%= link_to 'Edit', edit_pedido_path(@pedido) %> |
<%= link_to 'Back', pedidos_path %>